name: "🕷️ Bug report"
description: Report errors or unexpected behavior
labels:
  - Issue-Bug
  - Needs-Triage
body:
  - type: markdown
    attributes:
      value: Please make sure to [search for existing issues](https://github.com/leothinker/to-do-app/issues) before filing a new one!
  - id: version
    type: input
    attributes:
      label: To Do App version
      placeholder: X.XX.X
      description: Hover over the system tray icon or look at Settings
    validations:
      required: true

  - id: installed
    type: dropdown
    attributes:
      label: Installation method
      description: How / where was To Do App installed from?
      multiple: true
      options:
        - GitHub
        - To Do App auto-update
        - Other (please specify in "Steps to Reproduce")
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Area(s) with issue?
      description: What things had an issue? Check all that apply.
      multiple: true
      options:
        - General
        - Command not found
        - Settings
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including screenshots and a bug report log (System tray > Report bug).
      placeholder: Having detailed steps helps us reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false

  - id: additionalInfo
    type: textarea
    attributes:
      label: Additional Information
      placeholder: |
        OS version
        .Net version
        System Language
        User or System Installation
        Running as admin
    validations:
      required: false

  - type: textarea
    attributes:
      label: Other Software
      description: If you're reporting a bug about our interaction with other software, what software? What versions?
      placeholder: |
        vim 8.2 (inside WSL)
        OpenSSH_for_Windows_8.1p1
        My Cool Application v0.3 (include a code snippet if it would help!)
    validations:
      required: false
